version: '3.8'
services:
  mealplanner-api:
    container_name: mealplanner-api
    build:
      context: .
      target: production
    ports:
      - 3000:3000
    links:
      - postgres
    env_file:
      - .env
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: